### ISSUE TITLE
Checksum mismatch

### ISSUE THREAD

**Issue by MaticSincek** [felix/dhtsearch#1]
When trying to compile I'm getting a checksum mismatch:

verifying src.userspace.com.au/go-bencode@v0.3.0/go.mod: checksum mismatch
        downloaded: h1:L+JLhJUoAwVvkEhbpETP3Mli9qiRnDHlgQibYZZes6E=
        go.sum:     h1:x/2aZW6OnN60Ot7VCTShG1B7H47QaWRS7pCxkgCpfaI=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

Is this a go version issue? Which version whould I use?

Also if you have time, there is no schema.sql anymore, so the readme is somewhat misleading.

**Comment by MaoShultz** [comment]
Try adding `replace src.userspace.com.au/go-bencode => github.com/felix/go-bencode v0.3.0` in `go.mod`

**Comment by MaticSincek** [comment]
Tried adding it and it produced 
`build .: cannot find module for path .`
when building

**Comment by felix** [comment]
This should be fixed in 8685f1a. Sorry about the delay!
